name: docker_publish

on:
  push:
    branches:
      - 'main'
      - 'hiep/test'
    tags:
      - '*'
  pull_request:
    branches:
      - '**'

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@v0.7.0
    with:
      run-build: true
      run-unit-tests: true
      run-check-mock-gen: true
      run-gosec: true
      gosec-args: "-exclude-generated -exclude-dir=testutil ./..."

  docker_pipeline:
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@v0.7.0
    secrets: inherit
    with:
      publish: true
      repoName: finality-gadget
