name: docker_publish

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
  
jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@5d014a155c08d56a1b5673d049f2b4e7d4427825 # v0.19.0 https://github.com/babylonlabs-io/.github/releases/tag/v0.19.0
    with:
      go-version: "1.23.8"
      run-build: true
      run-unit-tests: true
      run-check-mock-gen: true
      run-gosec: true
      gosec-args: "-exclude-generated -exclude-dir=testutil ./..."

  docker_pipeline:
    needs: ["lint_test"]
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@5d014a155c08d56a1b5673d049f2b4e7d4427825 # v0.19.0 https://github.com/babylonlabs-io/.github/releases/tag/v0.19.0
    secrets: inherit
    with:
      publish: true
      repoName: finality-gadget
